// home/src/views/search.vue
<template>
  <div class="type">
    <header>
      <el-input
        placeholder="文章关键词"
        v-model="keyword"
        clearable
        class="search-text"
        @input="search"
      >
      </el-input>
    </header>
    <nav>
      <el-tag
        v-for="(item, index) in types"
        :key="item.type"
        :title="'查看关于' + item.type + '的文章'"
        @click="readTypeArticle(item.type), (acticeType = index)"
        :style="{ background: index === acticeType ? '#daebff' : '' }"
      >
        {{ item.type }}
      </el-tag>
    </nav>
    <article class="box" v-for="(item, index) in articleData" :key="index">
      <div class="article-head">
        <a class="article-title" :href="store.state.articleUrl + item.router">{{
          Base64.decode(item.title)
        }}</a>
        <time class="article-time">{{ item.time.substring(0, 10) }}</time>
      </div>
      <div class="article-text">{{ Base64.decode(item.introduce) }}</div>
      <p class="read">
        <a :href="store.state.articleUrl + item.router" target="_blank"
          >阅读全文»</a
        >
      </p>
    </article>
  </div>
  <el-empty
    description="没找到相应文章..."
    v-if="articleData.length == 0"
  ></el-empty>
</template>
<script setup>
import { onMounted, ref } from "vue";
import { Base64 } from "js-base64";
import { useStore } from "vuex";
import { useRoute } from "vue-router";
import { ElMessage } from "element-plus";
import readType from "@/modules/read-type";
import api from "@/modules/api";

let store = useStore();
let route = useRoute();

let types = ref();
let acticeType = ref("");
readType().then((res) => {
  types.value = res.data;
});
let articleData = ref([]);

// 初始化，查询置顶的文章
api(
  `SELECT * from article  WHERE isTop=1 and isShow=1 ORDER by time DESC;`
).then((res) => {
  articleData.value = res.res;
});

function readTypeArticle(type) {
  api(
    `SELECT * from article  WHERE type LIKE '%${type}%' and isShow=1 ORDER by time DESC;`
  ).then((res) => {
    articleData.value = res.res;
  });
}

// 如果是从用户端点击页脚的类型来的，就route带参数先根据参数搜索
if (route.query.type) {
  readTypeArticle(route.query.type);
}

let keyword = ref("");
let article = [];
onMounted(() => {
  api(`SELECT * from article WHERE isShow=1 ORDER by time DESC;`).then(
    (res) => {
      article = res.res;
    }
  );
});

function search() {
  articleData.value = [];
  let test = /^[\s\S]*.*[^\s][\s\S]*$/;
  article.forEach((item) => {
    let article = Base64.decode(item.title) + Base64.decode(item.introduce);
    if (article.indexOf(keyword.value) != -1) {
      articleData.value.push(item);
    }
  });
}
</script>
<style scoped lang='scss'>
header {
  margin-top: 20px;
  margin-left: 50px;
  .search-text {
    width: 400px;
    height: 40px;
  }
  .search-button {
    margin-left: 20px;
  }
}
nav {
  margin-top: 10px;
  margin-left: 50px;
  .el-tag {
    margin-left: 10px;
    cursor: pointer;
    &:first-child {
      margin-left: 0px;
    }
    &:hover {
      background: #daebff;
    }
  }
}

.box {
  padding: 5px 0px;
  border-bottom: 1px solid #ddd;
  border-top: 1px solid #fff;
}
.article-head {
  height: 50px;
  line-height: 50px;
  .article-title {
    font-weight: 400;
    font-size: 32px;
    color: #333;
    float: left;
    text-decoration: none;
    &:hover {
      color: #076dd0;
      cursor: pointer;
    }
  }
  .article-time {
    float: right;
    margin-right: 20px;
  }
}
.article-text {
  color: #444;
  padding: {
    top: 5px;
    bottom: 10px;
    right: 200px;
  }
}
.read {
  margin-top: 15px;
  margin-bottom: 20px;
  a {
    text-decoration: none;
    color: #076dd0;
  }
}
</style>

// home/src/page/search.jsx
import React, { Component } from "react";
import { Input, Tag, Empty } from "antd";
import { SearchOutlined } from "@ant-design/icons";
import { Base64 } from "js-base64";
import queryString from "query-string";
import "@/assets/scss/Search.scss";
import Article from "../components/Article";
import api from "../modules/api";

class Search extends Component {
  constructor(props) {
    super(props);
    this.state = {
      data: [],
      types: [],
      isType: "",
    };
    this.articleHub = [];
    this.searchArticle = this.searchArticle.bind(this);
    this.typeSeatch = this.typeSeatch.bind(this);
  }
  //   组件挂载之后就获取全部数组，然后查询,并察看类型
  componentDidMount() {
    api(`
    select * from article where isShow=1;
    select type from articletype;
    `).then(res => {
      this.articleHub = res.res[0];
      this.setState({
        types: res.res[1],
      });
    });

    const { type } = queryString.parse(this.props.location.search);
    if (type) {
      this.typeSeatch(type);
    }
  }
  searchArticle(value) {
    let articleData = [];
    this.articleHub.forEach((item, index) => {
      let text = Base64.decode(item.title) + Base64.decode(item.introduce);
      if (text.indexOf(value) !== -1) {
        articleData.push(item);
      }
    });
    this.setState({ data: articleData });
  }
  typeSeatch(type) {
    this.setState({ isType: type });
    api(`SELECT * from article WHERE type LIKE '%${type}%';`).then(res => {
      this.setState({ data: res.res });
    });
  }
  render() {
    return (
      <div id="search">
        <div className="type">
          <header>
            <Input
              size="large"
              placeholder="文章关键词"
              className="search-text"
              prefix={<SearchOutlined />}
              onInput={e => this.searchArticle(e.target.value)}
            />
          </header>
          <nav>
            {this.state.types.map((item, index) => {
              return (
                <Tag
                  color="blue"
                  key={index}
                  title={`查询关于${item.type}的文章`}
                  onClick={() => this.typeSeatch(item.type)}
                  style={{
                    background:
                      this.state.isType === item.type ? "#9ecbff" : "",
                  }}
                >
                  {item.type}
                </Tag>
              );
            })}
          </nav>
          <Article key="searchArticle" data={this.state.data} />
        </div>
        <Empty
          style={{ display: !!!this.state.data.length ? "block" : "none" }}
        />
      </div>
    );
  }
}
export default Search;
