// client/src/app/article/[id]/not-found.tsx
"use client";
import Head from "@/components/next/Head";
import { Result, Button } from "antd";
import Header from "@/components/common/Header";
import { useRouter } from "next/navigation";

const Error = () => {
  let router = useRouter();

  return (
    <>
      <Head title={`404-没有找到对应文章`} description={"404"} keywords={["404"]} />
      <Header />
      <Result
        status={"404"}
        title={"404"}
        subTitle="没有找到对应文章"
        extra={
          <Button type="primary" onClick={() => router.replace("/")}>
            回到首页
          </Button>
        }
      />
    </>
  );
};

export default Error;

// admin/src/page/NotFound.vue
<template>
  <el-result icon="error" title="没有找到对应的页面">
    <template #extra>
      <el-button type="primary" @click="router.back()">返回</el-button>
    </template>
  </el-result>
</template>
<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";
let router=useRouter()
</script>
<style scoped lang="scss"></style>
