// home/src/components/head.vue
<template>
  <!-- https://imququ.com/ -->
  <!-- 安这个样式改 -->
  <header>
    <img
      src="../assets/writer-face.png"
      alt="左侧导航栏作者头像"
      class="writer-face"
    />
    <nav>
      <h1 class="writer-name">{{ store.state.name }}</h1>
      <p class="write-text">WEB开发</p>
      <div class="nav">
        <router-link to="/">首页</router-link>
        <router-link to="/search">搜索</router-link>
        <router-link to="/resume">作者简历</router-link>
        <router-link to="/about">关于</router-link>
      </div>
      <div class="navs">
        <a href="https://github.com/Lrunlin">
          <img
            src="../assets/github.png"
            alt="作者GitHub"
            class="clearMargin"
          />
        </a>
        <a href="javascript:;" @click="isAlert = 'wechat'">
          <img src="../assets/wechat.png" alt="作者微信" />
        </a>
        <a href="javascript:;" @click="isAlert = 'qq'">
          <img src="../assets/qq.png" alt="作者QQ" />
        </a>
      </div>
    </nav>
  </header>
  <div class="alert" v-if="isAlert" @click="isAlert = null">
    <img
      src="@/assets/wechat-qrcode.jpg"
      alt="作者微信二维码"
      v-if="isAlert == 'wechat'"
      @click.stop=""
    />
    <img
      src="@/assets/qq-qrcode.jpg"
      alt="作者QQ二维码"
      v-if="isAlert == 'qq'"
      @click.stop=""
    />
  </div>
</template>
<script setup>
import { ref } from "vue";
import { useStore } from "vuex";
let store = useStore();

let isAlert = ref();
</script>
<style scoped lang='scss'>
header {
  width: 270px;
  height: 100vh;
  position: fixed;
  top: 0px;
  left: 0px;
  background-image: url("../assets/left-bg2.jpg");
  background-size: cover;
  .writer-face {
    width: 160px;
    border-radius: 50%;
    margin-left: 55px;
    margin-top: 50px;
  }
  nav {
    width: 160px;
    margin-left: 55px;
    .writer-name {
      font-weight: 400;
      color: white;
      margin-top: 15px;
    }
    .write-text {
      color: white;
      margin-top: 10px;
    }
    .nav {
      margin-top: 20px;
      a {
        text-decoration: none;
        display: block;
        height: 35px;
        line-height: 35px;
        color: #fff;
        text-shadow: 0 1px #666;
        font-size: 14px;
        &:hover {
          background-color: rgb(223, 223, 223, 0.1);
        }
      }
    }
    .navs {
      margin-top: 20px;
      img {
        width: 30px;
        margin-left: 5px !important;
      }
      .clearMargin {
        margin-left: 0px !important;
      }
    }
  }
}
.alert {
  position: fixed;
  top: 0px;
  left: 0px;
  width: 100vw;
  height: 100vh;
  z-index: 9999;
  background: rgb(0, 0, 0, 0.3);
  line-height: 100vh;
  text-align: center;
  img {
    width: 200px;
  }
}
</style>

// home/src/components/Head.jsx
import React, { Component } from "react";
import { NavLink } from "react-router-dom";
import "@/assets/scss/Head.scss";
import face from "@/assets/image/writer-face.png";
import github from "@/assets/image/github.png";
import wechat from "@/assets/image/wechat.png";
import qq from "@/assets/image/qq.png";
import wechatQrcode from "@/assets/image/wechat-qrcode.jpg";
import qqQrcode from "@/assets/image/qq-qrcode.jpg";

class Head extends Component {
  constructor(props) {
    super(props);
    this.state = {
      qrcodeShow: false,
    };
    this.hideQrcode = this.hideQrcode.bind(this);
    this.showQrcode = this.showQrcode.bind(this);
  }
  hideQrcode() {
    this.setState({ qrcodeShow: false });
  }
  showQrcode(type) {
    this.setState({ qrcodeShow: type });
  }
  render() {
    return (
      <header id="head">
        <img src={face} alt="左侧导航栏作者头像" className="writer-face" />
        <nav>
          <h1 className="writer-name">刘润霖</h1>
          <p className="write-text">WEB开发</p>
          <div className="nav">
            <NavLink exact to="/">
              首页
            </NavLink>
            <NavLink exact to="/search">
              搜索
            </NavLink>
            <NavLink exact to="/resume">
              作者简历
            </NavLink>
            <NavLink exact to="/about">
              关于
            </NavLink>
          </div>
          <div className="navs">
            <a href="https://github.com/Lrunlin">
              <img src={github} alt="作者GitHub" className="clearMargin" />
            </a>
            <span>
              <img
                src={wechat}
                alt="作者微信"
                className="show-qrcode"
                onClick={e => this.showQrcode("wechat")}
              />
            </span>
            <span>
              <img
                src={qq}
                alt="作者QQ"
                className="show-qrcode"
                onClick={e => this.showQrcode("qq")}
              />
            </span>
          </div>
        </nav>
        <div
          className="layer"
          style={{ display: this.state.qrcodeShow ? "block" : "none" }}
          onClick={() => this.hideQrcode()}
        >
          <img
            src={this.state.qrcodeShow === "wechat" ? wechatQrcode : qqQrcode}
            alt={`作者${
              this.state.qrcodeShow === "wechat" ? "微信" : "QQ"
            }二维码`}
          />
        </div>
      </header>
    );
  }
}
export default Head;
